### PR TITLE
Zipkin charts adding namespaces

### PR DESCRIPTION
**Pull request by mfordjody**
https://github.com/openzipkin/zipkin/pull/3531

### CODE REVIEW

**Comment by mfordjody** [comment]
@codefromthecrypt

**Comment by codefromthecrypt** [comment]
LGTM on green

**Comment by codefromthecrypt** [comment]
@mfordjody so the build failed because it expects a bump. if you check the log and correct that, happy to merge. I guess `charts/zipkin/Chart.yaml` should be 0.2.0 maybe

**Comment by mfordjody** [comment]
> @mfordjody so the build failed because it expects a bump. if you check the log and correct that, happy to merge. I guess `charts/zipkin/Chart.yaml` should be 0.2.0 maybe

Is the version 0.1.2 or 0.2.0 ？

**Comment by codefromthecrypt** [comment]
@mfordjody I don't mind, whatever is more conventional in k8s for something like adding a feature. you can choose either

**Comment by codefromthecrypt** [comment]
thanks @mfordjody!

**Comment by codefromthecrypt** [comment]
I did `git tag release-0.1.2;git push origin release-0.1.2`

**Pull request merged**
